name: sub-update
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 */3 * *"
  
jobs:
  process-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Download and Merge Rules
      run: |
        mkdir -p rules
        curl -o rules/subscription1.txt https://raw.githubusercontent.com/cobaltdisco/Google-Chinese-Results-Blocklist/master/uBlacklist_subscription.txt
        curl -o rules/subscription2.txt https://raw.githubusercontent.com/Paxxs/Google-Blocklist/develop/uBlacklist_subscription.txt
        curl -o rules/subscription3.txt https://raw.githubusercontent.com/arosh/ublacklist-stackoverflow-translation/master/uBlacklist.txt
        cat rules/subscription*.txt | sort -u > rules/all_rules.txt

    - name: Update JavaScript File
      run: |
        export urlFilter=$(grep -E -v '^title/' rules/all_rules.txt)
        export keywordsFilter=$(grep -E '^title/' rules/all_rules.txt)
        sed -i "s#const keywordsFilter =.*#const keywordsFilter = /$regex_rules_keywords/;#" filter.user.js.tmp
        # Extracting urlFilter and keywordsFilter from rules
        export urlFilter=$(awk '!/^title\// {printf "%s|", $0}' rules/all_rules.txt | sed 's/.$//')
        export keywordsFilter=$(awk '/^title\// {printf "%s|", $0}' rules/all_rules.txt | sed 's/.$//')
        sed -i "s#const urlFilter =.*#const urlFilter = /$urlFilter/;#" filter.user.js.tmp
        sed -i "s#const keywordsFilter =.*#const keywordsFilter = /$keywordsFilter/;#" filter.user.js.tmp

    - name: Add changes to the repository
      run: |
        git add .
        git status

    - name: Commit and push changes
      run: |
        git commit -m "rules update" -a
        git push