name: sub-update
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 */3 * *"
  
jobs:
  process-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Download and Merge Rules
      run: |
        mkdir -p rules
        curl -o rules/subscription1.txt https://raw.githubusercontent.com/cobaltdisco/Google-Chinese-Results-Blocklist/master/uBlacklist_subscription.txt
        curl -o rules/subscription2.txt https://raw.githubusercontent.com/Paxxs/Google-Blocklist@develop/uBlacklist_subscription.txt
        curl -o rules/subscription3.txt https://raw.githubusercontent.com/arosh/ublacklist-stackoverflow-translation/master/uBlacklist.txt
        cat rules/subscription*.txt | sort -u > rules/all_rules.txt

    - name: Process IPs and save to ./rules/cloudflare.list
      run: |
        wget https://www.cloudflare.com/ips-v4 -O cfv4.txt
        sed -i '/^[0-9.]\+\/[0-9]\+$/!d' cfv4.txt
        sed -i 's/^/IP-CIDR,/' cfv4.txt
        sed -i 's/$/,no-resolve/' cfv4.txt
        sed -i 's/$/\n/' cfv4.txt
        wget https://www.cloudflare.com/ips-v6 -O cfv6.txt
        sed -i '/^[0-9a-fA-F:]\+\/[0-9]\+$/!d' cfv6.txt
        sed -i 's/^/IP-CIDR6,/' cfv6.txt
        sed -i 's/$/,no-resolve/' cfv6.txt
        sed -i 's/$/\n/' cfv6.txt
        cat cfv4.txt cfv6.txt > rules/cloudflare.list.new
        mv -f rules/cloudflare.list.new rules/cloudflare.list
        rm -f cfv4.txt cfv6.txt
      
    - name: Add changes to the repository
      run: |
        git add .
        git status

    - name: Commit and push changes
      run: |
        git commit -m "Update IP CIDR list" -a
        git push