name: sub-update
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 */3 * *"
  
jobs:
  process-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Download and Merge Rules
      run: |
        mkdir -p rules
        curl -o rules/subscription1.txt https://raw.githubusercontent.com/cobaltdisco/Google-Chinese-Results-Blocklist/master/uBlacklist_subscription.txt
        curl -o rules/subscription2.txt https://raw.githubusercontent.com/Paxxs/Google-Blocklist/develop/uBlacklist_subscription.txt
        curl -o rules/subscription3.txt https://raw.githubusercontent.com/arosh/ublacklist-stackoverflow-translation/master/uBlacklist.txt
        cat rules/subscription*.txt | sort -u > rules/all_rules.txt

    - name: Update JavaScript File
      run: |
        rules_file="rules/all_rules.txt"
        keywordsFilter=()
        urlFilter=()
        while IFS= read -r line; do
          if [[ $line =~ ^title/.* ]]; then
            # 删除title/前缀
            line=${line:6}
            keywordsFilter+=("$line")
          elif [[ $line =~ ^\*://.* ]]; then
            # 转换为正则表达式
            line="^${line:3}$"
            urlFilter+=("$line")
          fi
        done < "$rules_file"

        keywordsFilter_regex=$(printf "|%s" "${keywordsFilter[@]}")
        keywordsFilter_regex=${keywordsFilter_regex:1}

        urlFilter_regex=$(printf "|%s" "${urlFilter[@]}")
        urlFilter_regex=${urlFilter_regex:1}

        echo "$keywordsFilter_regex" > keywordsrex.txt
        echo "$urlFilter_regex" > urlrex.txt

    - name: Add changes to the repository
      run: |
        git add .
        git status

    - name: Commit and push changes
      run: |
        git commit -m "rules update" -a
        git push